// src/components/HeroCard.tsx
import React from 'react';
import { Hero } from '../types';
import { useApp } from '../context/AppContext';

interface HeroCardProps {
  hero: Hero;
  onEdit: (hero: Hero) => void;
  onDelete: (id: string) => void;
}

export const HeroCard: React.FC<HeroCardProps> = ({ hero, onEdit, onDelete }) => {
  const { toggleFavorite, isFavorite } = useApp();
  const favorite = isFavorite(hero.id);

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('fr-FR', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });
  };

  return (
    <div className="hero-card">
      <div className="hero-card-image">
        {hero.image ? (
          <img src={hero.image} alt={hero.name} />
        ) : (
          <div className="no-image">Pas d'image</div>
        )}
        <button
          className={`favorite-btn ${favorite ? 'active' : ''}`}
          onClick={() => toggleFavorite(hero.id)}
          title={favorite ? 'Retirer des favoris' : 'Ajouter aux favoris'}
        >
          {favorite ? '★' : '☆'}
        </button>
      </div>
      
      <div className="hero-card-content">
        <h3>{hero.name}</h3>
        
        {hero.team && (
          <p className="hero-team">
            <span className="label">Équipe:</span> {hero.team}
          </p>
        )}
        
        <p className="hero-nemesis">
          <span className="label">Némésis:</span> {hero.nemesis}
        </p>
        
        <p className="hero-date">
          <span className="label">Première apparition:</span> {formatDate(hero.firstAppearance)}
        </p>
        
        {hero.labels.length > 0 && (
          <div className="hero-labels">
            {hero.labels.map((label) => (
              <span key={label} className="label-tag">
                {label}
              </span>
            ))}
          </div>
        )}
        
        <div className="hero-card-actions">
          <button className="btn-edit" onClick={() => onEdit(hero)}>
            Modifier
          </button>
          <button className="btn-delete" onClick={() => onDelete(hero.id)}>
            Supprimer
          </button>
        </div>
      </div>
    </div>
  );
};

// src/app/shared/components/hero-card/hero-card.component.ts
import { ChangeDetectionStrategy, Component, inject, input, output } from '@angular/core';
import { DatePipe, NgOptimizedImage } from '@angular/common';
import { Hero } from '../../models/hero.model';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-hero-card',
  standalone: true,
  templateUrl: './hero-card.component.html',
  styleUrls: ['./hero-card.component.scss'],
  imports: [DatePipe, NgOptimizedImage],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeroCardComponent {
  private readonly authService = inject(AuthService);

  hero = input.required<Hero>();
  heroEdit = output<Hero>();
  heroDelete = output<string>();

  get isFavorite(): boolean {
    return this.authService.isFavorite(this.hero().id);
  }

  formatDate(dateString: string): string {
    const date = new Date(dateString);
    return date.toLocaleDateString('fr-FR', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  }

  toggleFavorite(): void {
    this.authService.toggleFavorite(this.hero().id);
  }

  editHero(): void {
    this.heroEdit.emit(this.hero());
  }

  deleteHero(): void {
    this.heroDelete.emit(this.hero().id);
  }
}


<div class="hero-card">
  <div class="hero-card-image">
    @if (hero().image) {
      <img [src]="hero().image" [alt]="hero().name" />
    } @else {
      <div class="no-image">Pas d'image</div>
    }
    <button
      class="favorite-btn"
      [class.active]="isFavorite"
      (click)="toggleFavorite()"
      [title]="isFavorite ? 'Retirer des favoris' : 'Ajouter aux favoris'"
    >
      {{ isFavorite ? '★' : '☆' }}
    </button>
  </div>

  <div class="hero-card-content">
    <h3>{{ hero().name }}</h3>

    @if (hero().team) {
      <p class="hero-team">
        <span class="label">Équipe:</span> {{ hero().team }}
      </p>
    }

    <p class="hero-nemesis">
      <span class="label">Némésis:</span> {{ hero().nemesis }}
    </p>

    <p class="hero-date">
      <span class="label">Première apparition:</span> {{ formatDate(hero().firstAppearance) }}
    </p>

    @if (hero().labels.length > 0) {
      <div class="hero-labels">
        @for (label of hero().labels; track label) {
          <span class="label-tag">{{ label }}</span>
        }
      </div>
    }

    <div class="hero-card-actions">
      <button class="btn-edit" (click)="editHero()">Modifier</button>
      <button class="btn-delete" (click)="deleteHero()">Supprimer</button>
    </div>
  </div>
</div>
