// src/components/Login.tsx
import React, { useState } from 'react';
import { useApp } from '../context/AppContext';

export const Login: React.FC = () => {
  const { login, register } = useApp();
  const [isRegister, setIsRegister] = useState(false);
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    if (!username || !password) {
      setError('Veuillez remplir tous les champs');
      return;
    }

    if (isRegister) {
      const success = register(username, password);
      if (!success) {
        setError('Ce nom d\'utilisateur existe déjà');
      }
    } else {
      const success = login(username, password);
      if (!success) {
        setError('Identifiants incorrects');
      }
    }
  };

  return (
    <div className="login-container">
      <div className="login-box">
        <h1>Marvel Heroes Manager</h1>
        <h2>{isRegister ? 'Inscription' : 'Connexion'}</h2>
        
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="username">Nom d'utilisateur</label>
            <input
              type="text"
              id="username"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              placeholder="Entrez votre nom d'utilisateur"
            />
          </div>
          
          <div className="form-group">
            <label htmlFor="password">Mot de passe</label>
            <input
              type="password"
              id="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="Entrez votre mot de passe"
            />
          </div>
          
          {error && <div className="error-message">{error}</div>}
          
          <button type="submit" className="btn-primary">
            {isRegister ? 'S\'inscrire' : 'Se connecter'}
          </button>
        </form>
        
        <p className="toggle-mode">
          {isRegister ? 'Déjà un compte ? ' : 'Pas encore de compte ? '}
          <button
            type="button"
            className="link-button"
            onClick={() => {
              setIsRegister(!isRegister);
              setError('');
            }}
          >
            {isRegister ? 'Se connecter' : 'S\'inscrire'}
          </button>
        </p>
      </div>
    </div>
  );
};

// src/app/feature/login/login.component.ts
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
  imports: [FormsModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LoginComponent {
  private readonly authService = inject(AuthService);

  isRegister = signal(false);
  username = signal('');
  password = signal('');
  error = signal('');

  handleSubmit(): void {
    this.error.set('');

    if (!this.username() || !this.password()) {
      this.error.set('Veuillez remplir tous les champs');
      return;
    }

    if (this.isRegister()) {
      const success = this.authService.register(this.username(), this.password());
      if (!success) {
        this.error.set('Ce nom d\'utilisateur existe déjà');
      }
    } else {
      const success = this.authService.login(this.username(), this.password());
      if (!success) {
        this.error.set('Identifiants incorrects');
      }
    }
  }

  handleToggleMode(): void {
    this.isRegister.update((v) => !v);
    this.error.set('');
  }
}


<div class="login-container">
  <div class="login-box">
    <h1>Marvel Heroes Manager</h1>
    <h2>{{ isRegister() ? 'Inscription' : 'Connexion' }}</h2>

    <form (ngSubmit)="handleSubmit()">
      <div class="form-group">
        <label for="username">Nom d'utilisateur</label>
        <input
          type="text"
          id="username"
          [ngModel]="username()"
          (ngModelChange)="username.set($event)"
          name="username"
          placeholder="Entrez votre nom d'utilisateur"
        />
      </div>

      <div class="form-group">
        <label for="password">Mot de passe</label>
        <input
          type="password"
          id="password"
          [ngModel]="password()"
          (ngModelChange)="password.set($event)"
          name="password"
          placeholder="Entrez votre mot de passe"
        />
      </div>

      @if (error()) {
        <div class="error-message">{{ error() }}</div>
      }

      <button type="submit" class="btn-primary">
        {{ isRegister() ? 'S\'inscrire' : 'Se connecter' }}
      </button>
    </form>

    <p class="toggle-mode">
      {{ isRegister() ? 'Déjà un compte ? ' : 'Pas encore de compte ? ' }}
      <button type="button" class="link-button" (click)="handleToggleMode()">
        {{ isRegister() ? 'Se connecter' : 'S\'inscrire' }}
      </button>
    </p>
  </div>
</div>
