// src/app/shared/components/navigation/navigation.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-navigation',
  standalone: true,
  templateUrl: './navigation.component.html',
  styleUrls: ['./navigation.component.scss'],
  imports: [RouterLink, RouterLinkActive],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NavigationComponent {
  private readonly authService = inject(AuthService);

  currentUser = this.authService.currentUser;

  handleLogout(): void {
    this.authService.logout();
  }
}


<nav class="navbar">
  <div class="nav-container">
    <a routerLink="/" class="nav-logo">Marvel Heroes</a>

    <div class="nav-links">
      <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }">Tous les héros</a>
      <a routerLink="/favorites" routerLinkActive="active">Favoris</a>
      <a routerLink="/labels" routerLinkActive="active">Par labels</a>
      <a routerLink="/search" routerLinkActive="active">Recherche</a>
    </div>

    <div class="nav-user">
      <span class="username">{{ currentUser()?.username }}</span>
      <button (click)="handleLogout()" class="btn-logout">Déconnexion</button>
    </div>
  </div>
</nav>

// src/components/Navigation.tsx
import React from 'react';
import { Link, useLocation } from 'react-router-dom';
import { useApp } from '../context/AppContext';

export const Navigation: React.FC = () => {
  const { currentUser, logout } = useApp();
  const location = useLocation();

  const isActive = (path: string) => location.pathname === path;

  return (
    <nav className="navbar">
      <div className="nav-container">
        <Link to="/" className="nav-logo">
          Marvel Heroes
        </Link>
        
        <div className="nav-links">
          <Link to="/" className={isActive('/') ? 'active' : ''}>
            Tous les héros
          </Link>
          <Link to="/favorites" className={isActive('/favorites') ? 'active' : ''}>
            Favoris
          </Link>
          <Link to="/labels" className={isActive('/labels') ? 'active' : ''}>
            Par labels
          </Link>
          <Link to="/search" className={isActive('/search') ? 'active' : ''}>
            Recherche
          </Link>
        </div>
        
        <div className="nav-user">
          <span className="username">{currentUser?.username}</span>
          <button onClick={logout} className="btn-logout">
            Déconnexion
          </button>
        </div>
      </div>
    </nav>
  );
};
